#!/bin/sh
#
# EVOL DEVICES MQTT SENDER SCRIPT
# VER
VER="EVOL DEVICES MQTT SENDER SCRIPT v.20250322-1728"
# SETTINGS
MQTT_SRV=${1:-"YOUR_MQTT_SERVER"}
MQTT_P=1883
MQTT_USER=YOUR_MQTT_USERNAME
MQTT_PASS=YOUR_MQTT_PASSWORD
MQTT_TOPIC=${2:-"YOUR_MQTT_TOPIC"}
# VARS
#
UPTIME=$(uptime | sed -r 's/^.+ up ([^,]+), .+$/\1/')
SINCE=$(uptime -s)
SYS_FREE=$(free | awk '/Mem:/ {print $4}' | egrep '^[-+]?[0-9]*\.?[0-9]+$')
SYS_TOTAL=$(free | awk '/Mem:/ {print $2}' | egrep '^[-+]?[0-9]*\.?[0-9]+$')
TEMP=$(ipcinfo -t)
TEMPDALLAS0=$(ev_dallas)

if test "$MQTT_SRV" = "-h"; then
  echo "================================================" && echo $VER && echo "================================================"
  echo "Usage: [server] [topic]" && echo "Example: ./ev_mqtt mymqtt.org my_root_topic" && echo "Example: ./ev_mqtt 192.168.0.5 my_2root_topic"
else
        # SEND
        #
        mosquitto_pub -h "${MQTT_SRV}" -p "${MQTT_P}" -u "${MQTT_USER}" -P "${MQTT_PASS}" -t "${MQTT_TOPIC}/uptime" -m "${UPTIME}" -i "${MQTT_TOPIC}"
        mosquitto_pub -h "${MQTT_SRV}" -p "${MQTT_P}" -u "${MQTT_USER}" -P "${MQTT_PASS}" -t "${MQTT_TOPIC}/since" -m "${SINCE}" -i "${MQTT_TOPIC}"
        mosquitto_pub -h "${MQTT_SRV}" -p "${MQTT_P}" -u "${MQTT_USER}" -P "${MQTT_PASS}" -t "${MQTT_TOPIC}/freeheapmemory" -m "${SYS_FREE}000" -i "${MQTT_TOPIC}"
        mosquitto_pub -h "${MQTT_SRV}" -p "${MQTT_P}" -u "${MQTT_USER}" -P "${MQTT_PASS}" -t "${MQTT_TOPIC}/maxheapmemory" -m "${SYS_TOTAL}000" -i "${MQTT_TOPIC}"
        mosquitto_pub -h "${MQTT_SRV}" -p "${MQTT_P}" -u "${MQTT_USER}" -P "${MQTT_PASS}" -t "${MQTT_TOPIC}/temp" -m "${TEMP}" -i "${MQTT_TOPIC}"
        mosquitto_pub -h "${MQTT_SRV}" -p "${MQTT_P}" -u "${MQTT_USER}" -P "${MQTT_PASS}" -t "${MQTT_TOPIC}/tempDallas0" -m "${TEMPDALLAS0}" -i "${MQTT_TOPIC}"

fi

exit 0
